### ISSUE TITLE
Could use an example source directory

### ISSUE THREAD

**Issue by benwiley4000** [AlexBezuska/archival#1]
If the repo came with a directory of a few small sample images, and the config-sample.json could be copied to config.json and used in valid fashion without changing variables, this would make testing easier for contributors! 🙂

**Comment by AlexBezuska** [comment]
Yeah thats a good idea! I will let you know when I have that set up.

**Comment by AlexBezuska** [comment]
Thanks for the suggestion, I added the folder! https://github.com/AlexBezuska/archival/commit/cfd406b02c745c7a93031aee3c0bf070fa6cd426

**Comment by AlexBezuska** [comment]
btw I added a duplicate image in the folder on purpose, the next feature is going to remove duplicate files that have different names using [rdfind](https://rdfind.pauldreik.se/)

**Comment by benwiley4000** [comment]
Thanks!
